uri: https://raw.githubusercontent.com/datajoint/datajoint-file-validator/main/manifests/demo_bob_lab_frames_v0.1
id: bob_lab_frames
version: 0.1.0
description: Example of a fileset type for a Bob Lab fileset
author:
  name: Ethan Ho
  email: 53266718+ethho@users.noreply.github.com
rules:
  - id: num_files_constraint
    description: Check that there are between 1 and 5 files in the directory
    count_min: 1
    count_max: 5
